version: '3.8'

services:
  #Service 1: Our Python Chef
  flask-app:
    build: .
    container_name: backend-python
    expose:
      - "5000"

  # Service 2: The Nginx Waiter
  nginx:
    image: nginx:latest
    container_name: frontend-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask-app

  # Service 3: The Brain (Database)
  redis-db:
    image: "redis:alpine"
    container_name: database-redis

volumes:
  redis_data: